detect_duration: 10
camera_id: 0
enable_multithread_detect: true
retrack_queue_size: 10
fps: 75
send_posedata_udp: true
port: 4242
udp_host: 127.000.000.1
use_ft: false
use_npclient: false
cov_Q_lm: 0.089125093813374565
cov_Q_fsa: 0.095499258602143575
cov_T: 0.0010471285480508996
cov_V: 0.5745659676818673
cov_W: 28.336750230328732
ekf_predict_dt: 0.01
use_ekf: true
disp_duration: 30
disp_max_series_size: 10000
detect_method: 0
fsa_pnp_mixture_rate: 0.45000000000000001
hotkey_joystick_name0: Saitek Pro Flight X-55 Rhino Throttle
hotkey_joystick_button0: 1
hotkey_joystick_name1: ""
hotkey_joystick_button1: 0
landmark_detect_method: 0
pitch_offset_fsa_pnp: 0.191986218
cervical_face_model_x: 0.16
cervical_face_model_y: 0.16
cervical_face_model: -0.1